service: lms-backend
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  stage: dev
  environment:
    NODE_ENV: production
    # Set your environment variables or reference from AWS Parameter Store/Secrets Manager
    CLERK_PUBLISHABLE_KEY: ${env:CLERK_PUBLISHABLE_KEY}
    CLERK_SECRET_KEY: ${env:CLERK_SECRET_KEY}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    CLOUDFRONT_DOMAIN: ${env:CLOUDFRONT_DOMAIN}
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}

functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          path: /{proxy+}
          method: any

package:
  exclude:
#    - node_modules/**
    - .gitignore
    - .git/**
    - .env
  include:
    - dist/**
